name: Build and Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout main
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Node
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build project
      - name: Build project
        run: npm run build

      # Deploy dist to deployment branch
      - name: Deploy dist folder
        run: |
          git config --global user.name "pankajstagex"
          git config --global user.email "pankaj@stage-x.biz"

          # Switch to deployment branch, or create if not exists
          git fetch origin deployment
          git checkout deployment || git checkout --orphan deployment

          # Remove old files
          git rm -rf . || true

          # Copy new build
          rsync -av --progress dist/ . --exclude=.git

          # Commit and push
          git add .
          git commit -m "Deploy from main branch"
          git push origin deployment --force
